### ISSUE TITLE
Callback not called even after getting response

### ISSUE THREAD

**Issue by aman-gautam** [dreamfactorysoftware/angular-dreamfactory#10]
I am using the following code to send request to DSP.

```javascript
        $timeout(function(){
            DreamFactory.api.db.getRecords({table_name:'question'}, function(success){
                console.log(success);
            }, function(error){
                console.log(error);
            });
        });
```

The callbacks are getting called when this is first request I am sending but when it is followed by a POST (and PUT) request to the same end-point(`table_name`), the callbacks are not called.

I have confirmed in the Network tab of Developer console that the GET request is sent and the response is received.  

Is there a better way of getting the response?

**Comment by todda48** [comment]
This repo is only for DreamFactory 1.9.x and will go away soon. You should use DreamFactory 2.0.  Have a look at the angular-sdk repo. It's a sample app showing how to make CRUD calls to a db service.
