### ISSUE TITLE
For Apps hosted on DSP, module should also automatically check if user session is available on rest api

### ISSUE THREAD

**Issue by shankscoder** [dreamfactorysoftware/angular-dreamfactory#3]
When building an app that's hosted on the DSP, we want to use the DSP's login system to validate the user login workflow. It seems to me that the DSP Angular App should have the logic to check if the user session can be inherited from the DSP and populate the UserDataService accordingly.

As it stands, the use case for this module only works if you're using it on an app on an external hosting. IMO, it should facilitate building Apps to be hosted on the DSP itself.

**Comment by jstablesdf** [comment]
Closing dead issue.
